import Foundation

public struct DailyQuote {
    public let content: String
    public let author: String?
    public let title: String?
    
    public init(content: String, author: String? = nil, title: String? = nil) {
        self.content = content
        self.author = author
        self.title = title
    }
}

public class DailyQuoteManager {
    public static let shared = DailyQuoteManager()
    
    private let quotes: [DailyQuote] = [
        // 1月（31条）- 新年、冬季主题
        DailyQuote(content: "新的一年，愿你依然保持热爱，奔赴山海"),
        DailyQuote(content: "带着温暖的心，感受生活的美好"),
        DailyQuote(content: "愿你的生活既有诗意，也有烟火气"),
        DailyQuote(content: "把每一个平凡的日子，过成温暖的诗"),
        DailyQuote(content: "用心感受冬日里的每一缕暖阳"),
        DailyQuote(content: "生活的热爱，足以融化寒冬"),
        DailyQuote(content: "愿你眼里有光，心中有爱，前方有路"),
        DailyQuote(content: "把期待变成行动，把梦想变成现实"),
        DailyQuote(content: "新的篇章，写下属于你的故事"),
        DailyQuote(content: "用温暖的心，点亮寒冷的冬日"),
        DailyQuote(content: "在安静的时光里，遇见最好的自己"),
        DailyQuote(content: "愿生活总能给你一个温暖的拥抱"),
        DailyQuote(content: "等风来不如追风去，追逐的过程就是意义"),
        DailyQuote(content: "把理想放在生命的最高处"),
        DailyQuote(content: "愿你成为自己生命中的光"),
        DailyQuote(content: "以欢喜之心，过简单之生活"),
        DailyQuote(content: "在平凡的日子里，创造不平凡"),
        DailyQuote(content: "愿你的快乐与温暖，都能如约而至"),
        DailyQuote(content: "用心感受每一天的美好"),
        DailyQuote(content: "在寒冷的季节，遇见温暖的自己"),
        DailyQuote(content: "愿你的生活，既有诗情也有远方"),
        DailyQuote(content: "把每个梦想，都变成现实的模样"),
        DailyQuote(content: "在冬日里，与温暖相遇"),
        DailyQuote(content: "愿你的生活，充满温暖的色彩"),
        DailyQuote(content: "用心感受生活的美好"),
        DailyQuote(content: "让每一天都成为新的开始"),
        DailyQuote(content: "在平淡中，寻找生活的诗意"),
        DailyQuote(content: "愿你的生活，如愿以偿"),
        DailyQuote(content: "用温柔的心，对待这个世界"),
        DailyQuote(content: "让生活多一些诗意的温度"),
        DailyQuote(content: "在寒冷的季节里，保持内心的温暖"),

        // 2月（28条）- 春节、立春主题
        DailyQuote(content: "新的开始，新的希望，新的梦想"),
        DailyQuote(content: "愿你如春日般温暖，如春风般轻柔"),
        DailyQuote(content: "春天是最好的开始，遇见最美的自己"),
        DailyQuote(content: "让希望的种子在春天发芽"),
        DailyQuote(content: "春暖花开，岁月静好"),
        DailyQuote(content: "在春天里种下梦想的种子"),
        DailyQuote(content: "春风十里，不如你笑的样子"),
        DailyQuote(content: "把美好的期待种在春天里"),
        DailyQuote(content: "用温暖的心迎接春天的到来"),
        DailyQuote(content: "在春天里遇见更好的自己"),
        DailyQuote(content: "愿春风能温暖每个人的心"),
        DailyQuote(content: "让生活充满春天的气息"),
        DailyQuote(content: "在春日里寻找内心的平静"),
        DailyQuote(content: "愿你的心事都能随春风起舞"),
        DailyQuote(content: "用心感受春天的每一个瞬间"),
        DailyQuote(content: "让春天的温暖治愈所有的疲惫"),
        DailyQuote(content: "在春光里描绘美好的愿景"),
        DailyQuote(content: "愿春天带来新的希望"),
        DailyQuote(content: "用心感受春天的律动"),
        DailyQuote(content: "让春风吹散所有的烦恼"),
        DailyQuote(content: "在春天里找寻内心的声音"),
        DailyQuote(content: "愿春日里遇见最美的风景"),
        DailyQuote(content: "用温柔的心感受春天"),
        DailyQuote(content: "让春光温暖每个人的心"),
        DailyQuote(content: "在春天里寻找生活的诗意"),
        DailyQuote(content: "愿春风带来美好的消息"),
        DailyQuote(content: "用心感受春天的温度"),
        DailyQuote(content: "让春天成为最美的开始"),

        // 3月（31条）- 春分、踏青主题
        DailyQuote(content: "春天的脚步近了，愿你的心情也如春天般明媚"),
        DailyQuote(content: "在春光里寻找生活的美好"),
        DailyQuote(content: "让春天的气息温暖你的心"),
        DailyQuote(content: "愿你如三月的春风，温柔且坚定"),
        DailyQuote(content: "在春天里播种希望的种子"),
        DailyQuote(content: "用心感受春天的每一个细节"),
        DailyQuote(content: "让春风带走所有的疲惫"),
        DailyQuote(content: "在春光里遇见最好的时光"),
        DailyQuote(content: "愿春天带给你美好的心情"),
        DailyQuote(content: "用温柔的心感受春天的美"),
        DailyQuote(content: "让春光照亮前行的道路"),
        DailyQuote(content: "在春天里寻找内心的平静"),
        DailyQuote(content: "愿春风能吹散所有的阴霾"),
        DailyQuote(content: "用心感受春天的温暖"),
        DailyQuote(content: "让春天成为最美的季节"),
        DailyQuote(content: "在春光里描绘美好的未来"),
        DailyQuote(content: "愿春天带来新的希望"),
        DailyQuote(content: "用心感受春天的律动"),
        DailyQuote(content: "让春风吹散所有的烦忧"),
        DailyQuote(content: "在春天里寻找生活的意义"),
        DailyQuote(content: "愿春日里遇见美好的时光"),
        DailyQuote(content: "用温柔的心感受春天的气息"),
        DailyQuote(content: "让春光温暖每个人的心房"),
        DailyQuote(content: "在春天里寻找生活的诗意"),
        DailyQuote(content: "愿春风带来幸福的讯息"),
        DailyQuote(content: "用心感受春天的脉动"),
        DailyQuote(content: "让春天成为希望的开始"),
        DailyQuote(content: "在春光里感受生命的律动"),
        DailyQuote(content: "愿春天带来美好的改变"),
        DailyQuote(content: "用心描绘春天的色彩"),
        DailyQuote(content: "让春光照亮生活的每个角落"),

        // 4月（30条）- 清明、春暖主题
        DailyQuote(content: "愿你的生活如四月的春风，温柔且坚定"),
        DailyQuote(content: "在春天里播种梦想，在生活中收获感动"),
        DailyQuote(content: "让心中的温暖，照亮前行的路"),
        DailyQuote(content: "用心感受春天带来的惊喜"),
        DailyQuote(content: "愿生命如春天般充满活力"),
        DailyQuote(content: "在春光中寻找内心的宁静"),
        DailyQuote(content: "让每一天都充满希望和力量"),
        DailyQuote(content: "用温暖的心感知世界的美好"),
        DailyQuote(content: "在春天里遇见最真实的自己"),
        DailyQuote(content: "愿生活中有诗意的小确幸"),
        DailyQuote(content: "让春风带走所有的疲惫与烦恼"),
        DailyQuote(content: "用心感受生活的每个瞬间"),
        DailyQuote(content: "在春光里找寻内心的答案"),
        DailyQuote(content: "愿你的生活充满诗意与远方"),
        DailyQuote(content: "让温暖的阳光照亮前行的路"),
        DailyQuote(content: "用心感受四月的温柔"),
        DailyQuote(content: "在春天里遇见最美的风景"),
        DailyQuote(content: "愿生活如春天般充满希望"),
        DailyQuote(content: "让每一天都成为新的开始"),
        DailyQuote(content: "用温柔的心对待这个世界"),
        DailyQuote(content: "在春光里描绘美好的蓝图"),
        DailyQuote(content: "愿你的生活充满温暖与爱"),
        DailyQuote(content: "让春风吹散所有的阴霾"),
        DailyQuote(content: "用心感受生活的美好"),
        DailyQuote(content: "在春天里寻找内心的平和"),
        DailyQuote(content: "愿你的生活如诗如画"),
        DailyQuote(content: "让温暖的春光照亮心房"),
        DailyQuote(content: "用心感受春天的律动"),
        DailyQuote(content: "在春光里遇见最好的自己"),
        DailyQuote(content: "愿生活处处充满惊喜"),

        // 5月（31条）- 立夏、劳动主题
        DailyQuote(content: "愿你如五月的花般绚烂绽放"),
        DailyQuote(content: "用汗水浇灌梦想的种子"),
        DailyQuote(content: "让努力成为最好的奖励"),
        DailyQuote(content: "在劳动中收获生活的甜蜜"),
        DailyQuote(content: "愿你的付出都能开花结果"),
        DailyQuote(content: "用行动证明梦想的力量"),
        DailyQuote(content: "让每一天都充满奋斗的激情"),
        DailyQuote(content: "在努力中遇见最好的自己"),
        DailyQuote(content: "愿你的坚持都能看见彩虹"),
        DailyQuote(content: "用双手创造生活的美好"),
        DailyQuote(content: "让汗水见证成长的痕迹"),
        DailyQuote(content: "在奋斗中书写人生篇章"),
        DailyQuote(content: "愿你的梦想都能开花结果"),
        DailyQuote(content: "用心经营每一天的生活"),
        DailyQuote(content: "让付出成为最美的风景"),
        DailyQuote(content: "在劳动中感受生活的真谛"),
        DailyQuote(content: "愿你的努力都能开花结果"),
        DailyQuote(content: "用行动诠释生活的意义"),
        DailyQuote(content: "让每一天都充满希望"),
        DailyQuote(content: "在奋斗中遇见更好的自己"),
        DailyQuote(content: "愿你的坚持都能看见曙光"),
        DailyQuote(content: "用双手创造美好的明天"),
        DailyQuote(content: "让汗水浇灌希望的种子"),
        DailyQuote(content: "在努力中书写精彩人生"),
        DailyQuote(content: "愿你的梦想都能实现"),
        DailyQuote(content: "用心感受生活的美好"),
        DailyQuote(content: "让付出成为最美的回忆"),
        DailyQuote(content: "在劳动中收获幸福"),
        DailyQuote(content: "愿你的努力都有收获"),
        DailyQuote(content: "用行动创造美好生活"),
        DailyQuote(content: "让每一天都充满力量"),

        // 6月（30条）- 夏至、毕业主题
        DailyQuote(content: "愿你的未来如六月的阳光般灿烂"),
        DailyQuote(content: "带着梦想起航，怀着信念远行"),
        DailyQuote(content: "让青春在奋斗中绽放"),
        DailyQuote(content: "用勇气开启人生新篇章"),
        DailyQuote(content: "愿你的前路有光，脚下有路"),
        DailyQuote(content: "带着希望出发，怀着梦想前行"),
        DailyQuote(content: "让理想照亮前行的道路"),
        DailyQuote(content: "用信念托起明天的太阳"),
        DailyQuote(content: "愿你的未来充满无限可能"),
        DailyQuote(content: "带着勇气启程，怀着梦想远航"),
        DailyQuote(content: "让青春在追梦中闪耀"),
        DailyQuote(content: "用行动证明自己的价值"),
        DailyQuote(content: "愿你的人生如夏日般绚丽"),
        DailyQuote(content: "带着热情出发，怀着理想前进"),
        DailyQuote(content: "让梦想在奋斗中实现"),
        DailyQuote(content: "用努力创造美好的明天"),
        DailyQuote(content: "愿你的前途一片光明"),
        DailyQuote(content: "带着信心起航，怀着希望远行"),
        DailyQuote(content: "让青春在拼搏中绽放"),
        DailyQuote(content: "用坚持铺就成功的道路"),
        DailyQuote(content: "愿你的未来如期而至"),
        DailyQuote(content: "带着梦想前行，怀着勇气启程"),
        DailyQuote(content: "让理想在奋斗中闪光"),
        DailyQuote(content: "用行动书写精彩人生"),
        DailyQuote(content: "愿你的前方皆是光明"),
        DailyQuote(content: "带着希望启程，怀着信念前行"),
        DailyQuote(content: "让青春在追求中绽放"),
        DailyQuote(content: "用努力创造属于自己的未来"),
        DailyQuote(content: "愿你的梦想都能实现"),
        DailyQuote(content: "带着勇气前行，怀着梦想远航"),

        // 7月（31条）- 盛夏、追梦主题
        DailyQuote(content: "愿你如盛夏的骄阳，闪耀夺目"),
        DailyQuote(content: "带着炽热的心，追逐远方的梦"),
        DailyQuote(content: "让生命在热情中绽放光彩"),
        DailyQuote(content: "用奋斗的汗水浇灌梦想"),
        DailyQuote(content: "愿你的热情永不褪色"),
        DailyQuote(content: "在炎炎夏日里保持前进的动力"),
        DailyQuote(content: "让每一天都充满激情与活力"),
        DailyQuote(content: "用坚持创造生命的精彩"),
        DailyQuote(content: "愿你的梦想如夏日般炽热"),
        DailyQuote(content: "在追梦的路上永不言弃"),
        DailyQuote(content: "让生活在奋斗中更加精彩"),
        DailyQuote(content: "用行动证明梦想的价值"),
        DailyQuote(content: "愿你的坚持都开花结果"),
        DailyQuote(content: "在炎夏中保持内心的清凉"),
        DailyQuote(content: "让每个梦想都绽放光芒"),
        DailyQuote(content: "用热情点燃生命的激情"),
        DailyQuote(content: "愿你的付出都有回报"),
        DailyQuote(content: "在盛夏里书写人生篇章"),
        DailyQuote(content: "让努力成就最好的自己"),
        DailyQuote(content: "用信念支撑前行的脚步"),
        DailyQuote(content: "愿你的生活如夏日般绚丽"),
        DailyQuote(content: "在追梦路上永不停歇"),
        DailyQuote(content: "让每一天都充满希望"),
        DailyQuote(content: "用行动诠释生命的意义"),
        DailyQuote(content: "愿你的梦想从不言弃"),
        DailyQuote(content: "在炎炎夏日里保持前进"),
        DailyQuote(content: "让生活因奋斗而精彩"),
        DailyQuote(content: "用热情点亮生命的色彩"),
        DailyQuote(content: "愿你的努力都有收获"),
        DailyQuote(content: "在盛夏中追逐梦想"),
        DailyQuote(content: "让每一步都坚定有力"),

        // 8月（31条）- 立秋、收获主题
        DailyQuote(content: "愿你如八月的果实，饱满而丰盈"),
        DailyQuote(content: "在收获的季节里感恩付出"),
        DailyQuote(content: "让时光见证成长的痕迹"),
        DailyQuote(content: "用感恩的心迎接每一天"),
        DailyQuote(content: "愿你的付出都能开花结果"),
        DailyQuote(content: "在立秋时节感受生活的美好"),
        DailyQuote(content: "让每一天都充满感恩的心"),
        DailyQuote(content: "用平和的心看待得失"),
        DailyQuote(content: "愿你的努力都有回报"),
        DailyQuote(content: "在收获季节里品味生活"),
        DailyQuote(content: "让时光沉淀最美的记忆"),
        DailyQuote(content: "用感恩的心对待生活"),
        DailyQuote(content: "愿你的坚持都能看见彩虹"),
        DailyQuote(content: "在秋天里收获希望"),
        DailyQuote(content: "让每一天都充满感动"),
        DailyQuote(content: "用平静的心感受变化"),
        DailyQuote(content: "愿你的生活丰富多彩"),
        DailyQuote(content: "在收获的季节里遇见惊喜"),
        DailyQuote(content: "让时光见证成长的美好"),
        DailyQuote(content: "用感恩的心迎接秋天"),
        DailyQuote(content: "愿你的付出都有收获"),
        DailyQuote(content: "在立秋时节感受宁静"),
        DailyQuote(content: "让每一天都值得感恩"),
        DailyQuote(content: "用平和的心面对生活"),
        DailyQuote(content: "愿你的努力开花结果"),
        DailyQuote(content: "在收获季节里品味时光"),
        DailyQuote(content: "让生活充满感恩的心"),
        DailyQuote(content: "用平静的心迎接变化"),
        DailyQuote(content: "愿你的生活硕果累累"),
        DailyQuote(content: "在秋天里遇见最好的自己"),
        DailyQuote(content: "让每一天都充满希望"),

        // 9月（30条）- 秋分、思考主题
        DailyQuote(content: "愿你如九月的天空，澄澈明朗"),
        DailyQuote(content: "在秋分时节沉淀思考"),
        DailyQuote(content: "让内心沉静下来感受生活"),
        DailyQuote(content: "用智慧的眼光看待世界"),
        DailyQuote(content: "愿你的思考带来智慧"),
        DailyQuote(content: "在金秋时节寻找答案"),
        DailyQuote(content: "让每一天都充满思考"),
        DailyQuote(content: "用平静的心探索未知"),
        DailyQuote(content: "愿你的生活充满智慧"),
        DailyQuote(content: "在秋天里沉淀心灵"),
        DailyQuote(content: "让时光带来成熟的思考"),
        DailyQuote(content: "用理性的心看待世界"),
        DailyQuote(content: "愿你的思考开启智慧"),
        DailyQuote(content: "在秋分时节寻找方向"),
        DailyQuote(content: "让每一天都有新发现"),
        DailyQuote(content: "用冷静的心分析得失"),
        DailyQuote(content: "愿你的生活充满智慧"),
        DailyQuote(content: "在金秋里沉淀思绪"),
        DailyQuote(content: "让时光带来成长的智慧"),
        DailyQuote(content: "用理性的心探索生活"),
        DailyQuote(content: "愿你的思考带来启发"),
        DailyQuote(content: "在秋天里寻找真理"),
        DailyQuote(content: "让每一天都有新领悟"),
        DailyQuote(content: "用平和的心看待变化"),
        DailyQuote(content: "愿你的生活充满智慧"),
        DailyQuote(content: "在秋分时节沉淀心灵"),
        DailyQuote(content: "让时光带来深刻的思考"),
        DailyQuote(content: "用智慧的心感受生活"),
        DailyQuote(content: "愿你的思考开启新视界"),
        DailyQuote(content: "在金秋里遇见智慧"),

        // 10月（31条）- 国庆、金秋主题
        DailyQuote(content: "愿你如金秋的阳光，温暖而明亮"),
        DailyQuote(content: "在金秋时节感受生活的美好"),
        DailyQuote(content: "让心中充满对生活的热爱"),
        DailyQuote(content: "用欣赏的目光看待世界"),
        DailyQuote(content: "愿你的生活金灿灿的"),
        DailyQuote(content: "在秋高气爽中放飞梦想"),
        DailyQuote(content: "让每一天都充满感动"),
        DailyQuote(content: "用感恩的心看待收获"),
        DailyQuote(content: "愿你的付出都开花结果"),
        DailyQuote(content: "在金秋里品味生活"),
        DailyQuote(content: "让时光镀上金色的光芒"),
        DailyQuote(content: "用欢喜的心迎接收获"),
        DailyQuote(content: "愿你的生活丰富多彩"),
        DailyQuote(content: "在秋天里遇见最美的风景"),
        DailyQuote(content: "让每一天都值得珍惜"),
        DailyQuote(content: "用平和的心感受变迁"),
        DailyQuote(content: "愿你的生活金秋璀璨"),
        DailyQuote(content: "在收获的季节里感恩"),
        DailyQuote(content: "让时光沉淀最美的记忆"),
        DailyQuote(content: "用感激的心对待生活"),
        DailyQuote(content: "愿你的努力都有回报"),
        DailyQuote(content: "在金秋里品味时光"),
        DailyQuote(content: "让每一天都充满希望"),
        DailyQuote(content: "用欣赏的心看待世界"),
        DailyQuote(content: "愿你的生活硕果累累"),
        DailyQuote(content: "在秋天里遇见惊喜"),
        DailyQuote(content: "让时光见证成长的足迹"),
        DailyQuote(content: "用感恩的心迎接收获"),
        DailyQuote(content: "愿你的付出都有回报"),
        DailyQuote(content: "在金秋里感受幸福"),
        DailyQuote(content: "让每一天都充满感激"),

        // 11月（30条）- 立冬、沉淀主题
        DailyQuote(content: "愿你如深秋的枫叶，沉淀出最美的色彩"),
        DailyQuote(content: "在立冬时节感受内心的宁静"),
        DailyQuote(content: "让心沉淀下最美的时光"),
        DailyQuote(content: "用平静的心看待得失"),
        DailyQuote(content: "愿你的生活沉淀出智慧"),
        DailyQuote(content: "在深秋里寻找内心的答案"),
        DailyQuote(content: "让每一天都有新的感悟"),
        DailyQuote(content: "用冷静的心思考人生"),
        DailyQuote(content: "愿你的生活沉淀出真理"),
        DailyQuote(content: "在寒意中保持内心的温暖"),
        DailyQuote(content: "让时光沉淀最美的记忆"),
        DailyQuote(content: "用理性的心看待变化"),
        DailyQuote(content: "愿你的思考带来智慧"),
        DailyQuote(content: "在深秋里寻找方向"),
        DailyQuote(content: "让每一天都有新发现"),
        DailyQuote(content: "用平和的心对待生活"),
        DailyQuote(content: "愿你的生活沉淀出美好"),
        DailyQuote(content: "在寒意渐起时保持热情"),
        DailyQuote(content: "让时光带来成熟的智慧"),
        DailyQuote(content: "用冷静的心探索未来"),
        DailyQuote(content: "愿你的付出都有回报"),
        DailyQuote(content: "在深秋里品味生活"),
        DailyQuote(content: "让每一天都充满希望"),
        DailyQuote(content: "用平静的心迎接冬天"),
        DailyQuote(content: "愿你的生活沉淀出真谛"),
        DailyQuote(content: "在寒意中保持前进"),
        DailyQuote(content: "让时光沉淀最美的你"),
        DailyQuote(content: "用智慧的心看待世界"),
        DailyQuote(content: "愿你的思考开启新境界"),
        DailyQuote(content: "在深秋里遇见最好的自己"),

        // 12月（31条）- 冬至、总结主题
        DailyQuote(content: "愿你如冬日暖阳，温暖而有力量"),
        DailyQuote(content: "在岁末时光里总结收获"),
        DailyQuote(content: "让时光见证一年的成长"),
        DailyQuote(content: "用感恩的心回望这一年"),
        DailyQuote(content: "愿你的付出都有好结果"),
        DailyQuote(content: "在冬日里规划新的开始"),
        DailyQuote(content: "让每一天都充满期待"),
        DailyQuote(content: "用平和的心迎接新年"),
        DailyQuote(content: "愿你的努力都开花结果"),
        DailyQuote(content: "在寒冷中保持内心的温暖"),
        DailyQuote(content: "让时光定格最美的瞬间"),
        DailyQuote(content: "用感激的心总结得失"),
        DailyQuote(content: "愿你的生活充满希望"),
        DailyQuote(content: "在冬至时节感受温暖"),
        DailyQuote(content: "让每一天都值得期待"),
        DailyQuote(content: "用平静的心规划未来"),
        DailyQuote(content: "愿你的梦想都能实现"),
        DailyQuote(content: "在岁末里整装待发"),
        DailyQuote(content: "让时光见证成长的足迹"),
        DailyQuote(content: "用感恩的心迎接新年"),
        DailyQuote(content: "愿你的坚持都有回报"),
        DailyQuote(content: "在寒冷中保持热情"),
        DailyQuote(content: "让每一天都充满温暖"),
        DailyQuote(content: "用希望的心展望未来"),
        DailyQuote(content: "愿你的生活越来越好"),
        DailyQuote(content: "在冬日里保持前进"),
        DailyQuote(content: "让时光铭记美好回忆"),
        DailyQuote(content: "用感激的心迎接明天"),
        DailyQuote(content: "愿你的付出都有收获"),
        DailyQuote(content: "在岁末里遇见希望"),
        DailyQuote(content: "让新的一年充满可能")
    ]
    
    public func quoteForDate(_ date: Date) -> DailyQuote {
        let calendar = Calendar.current
        let dayOfYear = calendar.ordinality(of: .day, in: .year, for: date) ?? 1
        let index = (dayOfYear - 1) % quotes.count
        return quotes[index]
    }
} 
